            - نام: حافظه نهان
  موارد استفاده: actions/cache@v4.3.0
  با:
    # فهرستی از فایل‌ها، دایرکتوری‌ها و الگوهای wildcard برای ذخیره و بازیابی
    مسیر:
    # یک کلید صریح برای بازیابی و ذخیره حافظه پنهان
    کلید:
    # یک رشته چندخطی مرتب که کلیدهای منطبق با پیشوند را فهرست می‌کند، که برای بازیابی حافظه پنهان قدیمی در صورتی که هیچ ضربه‌ای به حافظه پنهان برای کلید رخ نداده باشد، استفاده می‌شوند. توجه داشته باشید که `cache-hit` در این مورد مقدار false را برمی‌گرداند.
    کلیدهای بازیابی: # اختیاری
    # اندازه تکه‌های مورد استفاده برای تقسیم فایل‌های بزرگ هنگام آپلود، بر حسب بایت
    اندازه-قطعه-بارگذاری: # اختیاری
    # یک مقدار بولی اختیاری که در صورت فعال بودن، به اجراکننده‌های ویندوز اجازه می‌دهد تا کش‌هایی را ذخیره یا بازیابی کنند که می‌توانند به ترتیب در پلتفرم‌های دیگر بازیابی یا ذخیره شوند.
    enableCrossOsArchive: # اختیاری، پیش‌فرض false است
    # اگر ورودی کش پیدا نشد، گردش کار با شکست مواجه می‌شود
    fail-on-cache-miss: # اختیاری، پیش‌فرض false است
    # بررسی کنید که آیا ورودی کش برای ورودی(های) داده شده (کلید، کلیدهای بازیابی) بدون دانلود کش وجود دارد یا خیر
    فقط جستجو: # اختیاری، پیش‌فرض نادرست است
    # مرحله‌ی post را اجرا کنید تا حافظه‌ی نهان ذخیره شود، حتی اگر مرحله‌ی قبل از آن با شکست مواجه شود
    ذخیره-همیشه: # اختیاری، پیش‌فرض نادرست است
          
